export const programmelist: Array<Programme> = [
  {
    title: "Klokken",
    description: "",
    pictureId: "5",
    id: 6,
  },
  {
    title: "Plus",
    description: "",
    pictureId: "151",

    id: 7,
  },
  {
    title: "Engelske ord",
    description: "",
    pictureId: "153",
    audioQuestion: true,
    usePictureAsAnswer: true,
    exerciseTitleInHeader: true,
    id: 8,
  },
  {
    title: "Minus",
    description: "",
    pictureId: "204",
    audioQuestion: false,
    exerciseTitleInHeader: false,
    id: 9,
  },
  {
    title: "Digitalt ur",
    description: "",
    pictureId: "261",
    audioQuestion: false,
    usePictureAsAnswer: true,
    exerciseTitleInHeader: false,
    id: 10,
  },
  {
    title: "Verdensdele",
    description: "",
    pictureId: "273",
    audioQuestion: false,
    usePictureAsAnswer: false,
    exerciseTitleInHeader: false,
    id: 11,
  },
  {
    title: "Halve og dobbelte",
    description: "",
    pictureId: "289",
    audioQuestion: false,
    usePictureAsAnswer: false,
    exerciseTitleInHeader: false,
    id: 12,
  },
  {
    title: "Rund af",
    description: "",
    pictureId: "290",
    audioQuestion: false,
    usePictureAsAnswer: false,
    exerciseTitleInHeader: false,
    id: 13,
  },
];
